var DATA = {
   "request" : {
      "country" : "uk",
      "language" : "en",
      "listing_type" : "rent",
      "location" : "London",
      "num_res" : "20",
      "offset" : 0,
      "output" : "json_xs",
      "page" : 1,
      "pretty" : "1",
      "product_type" : "realestate",
      "property_type" : "property",
      "size_type" : "gross",
      "size_unit" : "m2",
      "sort" : "nestoria_rank"
   },
   "response" : {
      "application_response_code" : "110",
      "application_response_text" : "listings returned, location very large",
      "attribution" : {
         "img_height" : 22,
         "img_url" : "http://s.uk.nestoria.nestimg.com/i/realestate/all/all/pbr.png",
         "img_width" : 183,
         "link_to_img" : "http://www.nestoria.com"
      },
      "created_http" : "Thu, 22 Oct 2015 16:38:14 GMT",
      "created_unix" : 1445531894,
      "link_to_url" : "http://www.nestoria.co.uk/london/property/rent/results-20",
      "listings" : [
         {
            "auction_date" : null,
            "bathroom_number" : 1,
            "bedroom_number" : 0,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Rightmove",
            "guid" : "g1-TNtATN1UjNyEzM=I",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/3/e/f/d5c1e13756b3eee27ea929c780fde2c586b70.2.jpg",
            "img_width" : 160,
            "keywords" : "Furnished, Grade II, High Ceilings, Kitchen, Lift, Porter, Near River, Listed",
            "latitude" : 51.5148200988769531,
            "lister_name" : "Cbre",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VaeKZSucbudSdVOul&s=&url=2-ePz73aTBU4LVGFByDI4_4Ner8aIMqOqmm3O6u5ws2qDemu6ceNje4Le1MAfGNkMMxpoFo0SuDqCXu_ZIEd28CChopBlbhxnBY1PXX1R-L_2uj1ayX9zSaUA3PPm9RTFzx1b6qhhXznLRVi4MvC7CXC1g_RXLsZSVtK_Ph7twCHaTlCV2Cj_aaWAreFEzfhXFT-qfRCrLDrDf6WSc-pIhgi3qlsbSL0gLeoiUJL0AptTW26OIJWtJ9LPnrfwtVQBdL-D38BfMEjAvzaGCsRyKE1HAEqZL50B0-Heg89xt7XTBdjjkOAcyUA5USLLNAIjHmCNbl8ZB0GCHdCQQYWvV_o0nj7630LYCUWkeh2J8nLVYyXHwIUm4NM1PqYVcqLNX98w_kNJuZlRvsFmc7ZnSCRFxcg%3D%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.10805000364780426,
            "price" : 425,
            "price_currency" : "GBP",
            "price_formatted" : "425 GBP per week",
            "price_high" : 425,
            "price_low" : 425,
            "price_type" : "weekly",
            "property_type" : "",
            "summary" : "Studio apartment to rent is tucked away in a pedestrian courtyard called...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/3/e/f/d5c1e13756b3eee27ea929c780fde2c586b70.1.jpg",
            "thumb_width" : 60,
            "title" : "Bolt Court, London, EC4 - Lift",
            "updated_in_days" : 2.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 1,
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Property Pigeon",
            "guid" : "g1-TOtUTMyADO1EzM=A",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/4/f/c/774508baa1ddafae156dbc20ab8b9b58343a0.2.jpg",
            "img_width" : 160,
            "keywords" : "Furnished, Penthouse, Kitchen",
            "latitude" : 51.5177192687988281,
            "lister_name" : null,
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VVeFUNpXWpYNYQJph&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmm3O6u5ws2qDemu6ceNje4Le1MAfGNUMMxpoEo0SuDqCXu_ZIEd28CS5mphlbhxnBY1PUUFR-L_2uj1ayX9zSaUA3PPm9RTFzx1X6rxhXznLRVi4MvC7CXC1g_RnOsZWSvKjDhLtwCHeflCRwBDnaaWAreFEzfhXFT-qfRCrLDrDf6WaH8oownTblg4HWJQkQP8SLeKcb7NbQzf6ZODJCvK724_48Ul9ZMfDpvFacCGMv0qOErU3KTA7HVOUExQ%3D%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 9,
            "longitude" : -0.0662499964237213135,
            "price" : 720,
            "price_currency" : "GBP",
            "price_formatted" : "720 GBP per week",
            "price_high" : 720,
            "price_low" : 720,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Fine example of a beautifully presented, two double bedroom Penthouse...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/4/f/c/774508baa1ddafae156dbc20ab8b9b58343a0.1.jpg",
            "thumb_width" : 60,
            "title" : "London Fruit Exchange, Brushfield St, E1",
            "updated_in_days" : 2.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : 1,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Home.co.uk",
            "guid" : "g1-DOtUTM1IjN1AjM5QgM==",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/d/e/7/fd56a4749ce4aa327d6578ebe19bf4d435c63.2.jpg",
            "img_width" : 160,
            "keywords" : "Terrace, Conversion",
            "latitude" : 51.4807815551757812,
            "lister_name" : "KF&H",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=UZe.OHjRQjSHSKDjc&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqmnnO6u5ws2qDemu6ceNje4Le1MAjFN0MMxpoEo0SuDqCXu_ZIEd28CCljpRVbhxnBYlrTUF5-L_2uj1ayX9zSaUA3PPm9RTFzx1P9qQQMjxnURFxT7SCTTGx45QLDqYuTtaLNh65sDnKUlyNwCzDLZ258f099Zg2PU-qbDj_LVrDfsDid8pcwwSHz3Z3abwARY_iWM7wE7MXOw_6UKytk47Ly5tMzVR5cMvrRrlXACGpxnPPE9huQQU2NCKJDykdisDTxo9czvTWBIHirP1MoSV5lQKTdBo_DxHND&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.113190002739429474,
            "price" : 360,
            "price_currency" : "GBP",
            "price_formatted" : "360 GBP per week",
            "price_high" : 360,
            "price_low" : 360,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "One bedroom apartment within a Hospital conversion on Clapham Road...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/d/e/7/fd56a4749ce4aa327d6578ebe19bf4d435c63.1.jpg",
            "thumb_width" : 60,
            "title" : "Clapham Road London, SW9 - Terrace",
            "updated_in_days" : 4.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 1,
            "bedroom_number" : 1,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "The House Shop",
            "guid" : "g1-zNtEDOxUDN4k",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/e/d/2/ecdee994f2aeaf560207cd72ffa4347b50e69.2.jpg",
            "img_width" : 160,
            "keywords" : "Kitchen, Modern",
            "latitude" : 51.5023612976074219,
            "lister_name" : "Faron Sutaria",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=WdeXmf7po7qfqib71&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqmn3O6u5ws2qDemu6ceNje4Le1MAjEMEMMxpoEo0SuDqCXu_ZIEd28Cyplox1bhxnBY1LRVFB-L_2uj1ayX9zSaUA3PPm9RTFzx1P7qwMMjxnURFxT7SCTTGx45QLMrYuRvK7Og6FsDnKWlSBzBj7JZ258f099Zg2PU-qbDnbeVujfsGHb6ZIwhy3pgI3CKAkOP8SLO_0AscnSx_yIM2tP_vDh5-IrFRxXM_Dhsw-OFjQzx-PAsEzLTwnGX-1TzF5E_mq25IJmtWnQaj7iK0gmAhZ_SIjEDJnD0DwDl8ZWxiOW&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.225710004568099976,
            "price" : 311,
            "price_currency" : "GBP",
            "price_formatted" : "311 GBP per week",
            "price_high" : 311,
            "price_low" : 311,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "One bedroom flat in an ideal location. Consists of a open-plan...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/e/d/2/ecdee994f2aeaf560207cd72ffa4347b50e69.1.jpg",
            "thumb_width" : 60,
            "title" : "Market Studio, Goldhawk Rd, Shepherds Bush London, W12",
            "updated_in_days" : 12.5,
            "updated_in_days_formatted" : "last week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : "",
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "London2let.com",
            "guid" : "g1-TOtcDTMJjM1kSNx0TM3M",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/b/b/9/c15b4512bdc8ad0abcb869c99b252992b7a2d.2.jpg",
            "img_width" : 160,
            "keywords" : "",
            "latitude" : 51.5083084106445312,
            "lister_name" : "Next property",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=WceWle6on6pepha61&s=&url=2-ePz73aTBU4OSRgFhBpsi8Mu5v7MGuPajmG6ippo3373Uhu-Be8LD56OvP1eQa0wF1IcEr1m4XP3ItflbEtiiASthtgBV3lzNbECRRUp-c62rmBGqR4zFcVRrObyZYkNrmE7q7FcC2BeqMSFCqDmCBzl37hfIr5eVta7Kk7pjSjfLhitmW32MNXhxJUpmMxnBVPCLEWvWFaLc6XWa8NUlnS3slprFOUkyI-vWb-dF7peTkbnTaDs%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 9,
            "longitude" : -0.145799994468688965,
            "price" : 546,
            "price_currency" : "GBP",
            "price_formatted" : "546 GBP per week",
            "price_high" : 546,
            "price_low" : 546,
            "price_type" : "weekly",
            "property_type" : "",
            "summary" : "3rd floor office to let: charles street, london, w1j- 180 sq ftlocation:...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/b/b/9/c15b4512bdc8ad0abcb869c99b252992b7a2d.1.jpg",
            "thumb_width" : 60,
            "title" : "Charles Street, Mayfair London, W1",
            "updated_in_days" : 4.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 2,
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "NetHousePrices",
            "guid" : "g1-TOtATQxUER4UUQ3UkMEJDOfZjM0IjN3IQN==",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/f/2/7/a83694dce8ae01e3d6607df10827e6cbf3a41.2.jpg",
            "img_width" : 160,
            "keywords" : "Unfurnished, En suite, Balcony, Kitchen, Lift, Parking, Reception, Modern",
            "latitude" : 51.4816513061523438,
            "lister_name" : "Featherstone Leigh",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=XUeYng8qp8rgrjc84&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmn3O6u5ws2qDemu6ceNje4Le1MAjEMEMMxpoEo0SuDqCXu_ZIEd28CilkpB9bhxnBYlrSUVN-L_2uj1ayX9zSaUA3PPm9RTFzx1D5rwQMjxnURFxT7SCTTGx45QLCrIuQtazOhqdsDnKUlShzADzJZ258f099Zg2PU-qbDj_LVqnNs36a6IkwnzD1kI3CbgURfIiUJL0AptTW26GYLzJa-LHgrc1qCzR9ZdXL6hC7Yz4ooKCCq0LMSQjQK71I3Fx1qDfzxI5i7CKHWm-_aWM1QQ1_Q7jbDdiYlQVpyYxBx2-fbXcXY0HE_IVqgLKjyuQeXXtIlQ%3D%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 9,
            "longitude" : -0.314029991626739502,
            "price" : 484,
            "price_currency" : "GBP",
            "price_formatted" : "484 GBP per week",
            "price_high" : 484,
            "price_low" : 484,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Two bedroom, two bathroom apartment in a brand new development in...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/f/2/7/a83694dce8ae01e3d6607df10827e6cbf3a41.1.jpg",
            "thumb_width" : 60,
            "title" : "London Road, Brentford, Middlesex, TW8",
            "updated_in_days" : 20.5,
            "updated_in_days_formatted" : "two weeks ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 1,
            "bedroom_number" : 1,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "HomeBoard",
            "guid" : "g1-TOtk2Lpx3cpRmbvcDNwAjN2cwL==",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/7/7/9/6837a59617e70210675a54cbef4c3c7230900.2.jpg",
            "img_width" : 160,
            "keywords" : "Floorplan, Terrace, Kitchen, Loft, Parking, Reception",
            "latitude" : 51.5256004333496094,
            "lister_name" : "Greene",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=UVe7KDfNMfODOG.fc&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqmm3O6u5ws2qDemu6ceNje4Le1MAfGNkMMxpoEo0SuDqCXu_ZIEd28CChkoR5bhxnBY1DWUVZ-L_2uj1ayX9zSaUA3PPm9RTFzx1H4rAAMjxnURFxT7SCTTGx45QLCpYuRuqjPga9sDnKVlCB3AjrIZ258f099Zg2PU-qbDj_LVrDfsDiB9Z89gC_5kYfQMgJQcsjKI7lfr8_R1ueSLWkPoe2ltbpwC11aOPCju06YUyt4kOCd7RGQChCWCf9W2Udv6Hetu4ls_XTQNDn5dEsoTA0mVqPbDJjeiDJSlNFYx2-cNz0IIVjZ8YQ4gPq13boaFmc%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 9,
            "longitude" : -0.104520000517368317,
            "price" : 700,
            "price_currency" : "GBP",
            "price_formatted" : "700 GBP per week",
            "price_high" : 700,
            "price_low" : 700,
            "price_type" : "weekly",
            "property_type" : "",
            "summary" : "Brand new to the market is this apartment in one of clerkenwells pioneering...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/7/7/9/6837a59617e70210675a54cbef4c3c7230900.1.jpg",
            "thumb_width" : 60,
            "title" : "Pattern House, St. John St, Clerkenwell London, EC1",
            "updated_in_days" : 132.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 2,
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Rightmove",
            "guid" : "g1-TNtAzMwcTO3AjN=c",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/4/6/5/0aaed18130ee83f332b190c233d92131d87cc.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Furnished, Conversion, Victorian",
            "latitude" : 51.4585113525390625,
            "lister_name" : "KF&H",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VUeETMoWVoXMXPIom&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmnnO6u5ws2qDemu6cetje4Le1MAjFN0MMxpoFo0SuDqCXu_ZIEd28CC9hpxpbhxnBYlfbUld-L_2uj1ayX9zSaUA3PPm9RTFzx1f9rxhXznLRVi4MvC7CXC1g_RXLsZKUuqvPnKd2DHGXnCJ2CivUZzcsZh8rZl_ZT-7VUSqTDrCGtX-S9Y44gDT53YvebhMVPteWOaIVsdLbj_qTZzRe_6m88v4wShVKKe2j7hXJHjYpyaWe9wCTEgKKE795y1xu_2amq49m-3PaayPsf1QzSTxmQLPAHJCX1zRYlNFBw23NJyUJU1fX8pA2h7C-g-UJR24Fmnl0wftPwmvtJkDhLJ5OsLdgpLJN5scl2YFlcFN0rUKUsPbAdA0u&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.171360000967979431,
            "price" : 550,
            "price_currency" : "GBP",
            "price_formatted" : "550 GBP per week",
            "price_high" : 550,
            "price_low" : 550,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Two double bedroom, two bathroom split level Victorian conversion to rent...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/4/6/5/0aaed18130ee83f332b190c233d92131d87cc.1.jpg",
            "thumb_width" : 60,
            "title" : "Chivalry Road London, SW11 - Garden",
            "updated_in_days" : 2.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 1,
            "bedroom_number" : 1,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Property Pigeon",
            "guid" : "g1-TOtUTMzATOwMTO=A",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/e/f/b/6054209e97d73066c512a3e955ce097a0ea3d.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Furnished, Kitchen, Parking",
            "latitude" : 51.5780792236328125,
            "lister_name" : null,
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VYeIXQsaZsbQbTMsr&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqmnHO6u5ws2qDemu6ceNje4Le1MAfCM0MMxpoEo0SuDqCXu_ZIEd28CCFnrBxbhxnBY1XbV15-L_2uj1ayX9zSaUA3PPm9RTFzx1D8rRhXznLRVi4MvC7CXC1g_RnOsZWSvKjDhLtwCHaXlyNyBTzaaWAreFEzfhXFT-qfRCrLDrDf6WaH8oownTblg4HWJQkQP8SLeKcb7NbQzf6ZODJCvK724_48Ul9fMvjquFCKCmFsmvfesBqJTwzSVuUVjgMvvj3wocN-&v=2",
            "listing_type" : "let",
            "location_accuracy" : 9,
            "longitude" : -0.197799995541572571,
            "price" : 242,
            "price_currency" : "GBP",
            "price_formatted" : "242 GBP per week",
            "price_high" : 242,
            "price_low" : 242,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "1 bedroom flat with open plan living room and kitchen and bathroom, brand...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/e/f/b/6054209e97d73066c512a3e955ce097a0ea3d.1.jpg",
            "thumb_width" : 60,
            "title" : "Flat to rent, London, NW11 - Kitchen",
            "updated_in_days" : 6.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : 1,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Rightmove",
            "guid" : "g1-TNtAzMwcTO3AzN=A",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/2/4/c/dbe7b8da71d1625f14c00177b0f99aad5d5b5.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Unfurnished, Refurbished, Wood Floor, Kitchen, Patio, Modern",
            "latitude" : 51.4722518920898438,
            "lister_name" : "KF&H",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VYeIXQsaZsbQbTMsji&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqmnnO6u5ws2qDemu6cetje4Le1MAjFN0MMxpoEo0SuDqCXu_ZIEd28CC5orRRbhxnBYlXRVVN-L_2uj1ayX9zSaUA3PPm9RTFzx1HwrxhXznLRVi4MvC7CXC1g_RXLsZKUuqvPnKd2DHGXnCJ3ByvUZzcsZh8rZl_ZT-7VUSqTDrCGtX-S9Y44gDT53YvebhMVPteWOaIVsdLbj_qTZzRe_6m88v4wShVKKe2j7hXJHjYpyKKe9wCTEgKKE795y1xu_2amq49m-3PaayPsf1QzSTxmQLPAHJCX1zRYlNFBw23NJyUJU1fX8pA2h7C-g-UJR24Fmnl0wftPwmvtJkDhLJ5OsLdgpLJN5scl2YFlcFN0rUKUsPbAdA0u&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.168980002403259277,
            "price" : 380,
            "price_currency" : "GBP",
            "price_formatted" : "380 GBP per week",
            "price_high" : 380,
            "price_low" : 380,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Newly refurbished one double bedroom garden flat to rent minutes from...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/2/4/c/dbe7b8da71d1625f14c00177b0f99aad5d5b5.1.jpg",
            "thumb_width" : 60,
            "title" : "Bullen Street London, SW11 - Patio",
            "updated_in_days" : 2.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : 1,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Home.co.uk",
            "guid" : "g1-DOtUTM1IjN1ATOyAQN==",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/4/c/2/73bedd5760b82408136da35b8aec3a9c06406.2.jpg",
            "img_width" : 160,
            "keywords" : "Unfurnished, Conversion, Refurbished",
            "latitude" : 51.4678916931152344,
            "lister_name" : "KF&H",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=UXe9MFhPOhQFQIBhYY&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqmnnO6u5ws2qDemu6ceNje4Le1MAfMNkMMxpoFo0SuDqCXu_ZIEd28CS5noBRbhxnBYlTUX19-L_2uj1ayX9zSaUA3PPm9RTFzx1P6qgQMjxnURFxT7SCTTGx45QLDqYuTtaLNh65sDnKUlyNwCzrPZ258f099Zg2PU-qbDj_LVrDfsDid8pcwwSHz3Z3abwARY_iWM7wE7NTbx9GQKyhezrH87OgwVC9LOKW78k6WRGdqlv3eoASMEU2aFaZfhQIpuDPzo9gzujKTfzjiNBwpQRB_SqXACN_X&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.0674799978733062744,
            "price" : 288,
            "price_currency" : "GBP",
            "price_formatted" : "288 GBP per week",
            "price_high" : 288,
            "price_low" : 288,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "One bedroom conversion flat to rent on Rye lane in Peckham. Newly...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/4/c/2/73bedd5760b82408136da35b8aec3a9c06406.1.jpg",
            "thumb_width" : 60,
            "title" : "Rye Lane London, SE15 - Refurbished",
            "updated_in_days" : 4.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 2,
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Rightmove",
            "guid" : "g1-TNtAzMwcDNxIjM=U",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/9/7/a/8c4967309aeb8835b6dc5b0395e33dec7705e.2.jpg",
            "img_width" : 160,
            "keywords" : "New Build, Balcony, Wood Floor",
            "lister_name" : "KF&H",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VdeNcVxfexgVgYRxop&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmnnO6u5ws2qDdmu6cetje4Le1MAjFN0MMxpoFo0SuDqCXu_ZIEd28CC9joBhbhxnBYlXRVFF-L_2uj1ayX9zSaUApK-eBQmYgiQbqpQUMwEXhb28UsjaTCzxi81fX2-Tyr-bWk-UiHX-FkSFpBz_PdXdzOwoidgCdAqfZXCnGDLXE5SzX9Y4hn3iz3J_GN0gMeMCMIr8ftcOMweHSPy0U4a_88uktTgkVKfujr0eXUylujf3A-gaKBxDMUOISigIpuCur4oxvt3LBdBX-NlQ1RwY2S7LaHZLYzDAYhNde_WyONjgRYQnE-oYynKWx0q0ZQHc1i3F4jehDy3G5JkKsfoRItIk_ublX98A_g9EmdlN2gEia4tHyJFtuYRgF5380GdlS1CmKGK0%3D&v=2",
            "listing_type" : "let",
            "price" : 438,
            "price_currency" : "GBP",
            "price_formatted" : "438 GBP per week",
            "price_high" : 438,
            "price_low" : 438,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Two double bedroom, two bathroom new build apartment to rent minutes from...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/9/7/a/8c4967309aeb8835b6dc5b0395e33dec7705e.1.jpg",
            "thumb_width" : 60,
            "title" : "Parkham Street London, SW11 - Balcony",
            "updated_in_days" : 10.5,
            "updated_in_days_formatted" : "last week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Home.co.uk",
            "guid" : "g1-DOtUTM1IjNzATM4UwN==",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/2/6/7/76d7595873414d0cab4973ec40ed5a30cd82d.2.jpg",
            "img_width" : 160,
            "keywords" : "Refurbished",
            "latitude" : 51.4831085205078125,
            "lister_name" : "Houseladder",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VbeLaTvdcveTeWPvmo&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmn3O6u5ws2qDemu6ceNje4Le1MAjEMEMMxpoEo0SuDqCXu_ZIEd28CCFioBRbhxnBYlrQVld-L_2uj1ayX9zSaUA3PPm9RTFzx1D6rwQMjxnURFxT7SCTTGx45QLDqYuTtavDgaVsDnKUliZ9AjvAZ258f099Zg2PU-qbDj_LVrDfsDid8pcwwSHz3Z3abwARY_iWM7wE7MrNzOqTJBlc47jy9uktZRxXM_Dhsw2VSGV_i_vf8UuODFKPAqBSwQ4qvzD1ptIyvT-CPyz_Nkx6SgZ4UbjbAJyI2A%3D%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.192479997873306274,
            "price" : 507,
            "price_currency" : "GBP",
            "price_formatted" : "507 GBP per week",
            "price_high" : 507,
            "price_low" : 507,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Newly refurbished 2 Bedroom flat in Earls Court. Looking for minimum 12...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/2/6/7/76d7595873414d0cab4973ec40ed5a30cd82d.1.jpg",
            "thumb_width" : 60,
            "title" : "Flat for rent, London, SW6",
            "updated_in_days" : 8.5,
            "updated_in_days_formatted" : "last week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 2,
            "bedroom_number" : 3,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Property Pigeon",
            "guid" : "g1-TOtUTM1AzN3IDM=E",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/4/b/2/ad40161e9df234d3f46a46cf24a80fb64d254.2.jpg",
            "img_width" : 160,
            "keywords" : "En suite, New Build, Balcony, Kitchen, Porter, Reception, Modern",
            "latitude" : 51.4811592102050781,
            "lister_name" : null,
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VYeIXQsaZsbQbTMsjm&s=&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOqmnnO6u5ws2qDdmu6ceNje4Le1MAjFN0MMxpoEo0SuDqCXu_ZIEd28CCtjoRpbhxnBYlrSVlB-L_2uj1ayX9zSaUApK-eBQmYgiQbqpQUMwEXhb28UsjaTDj9q7wyMsOHg3bmHnbQyXGedhihxHjrIdHFnPxAgcwSeDq7aSzfGVeXdtXrXp9g9mzbsyceeNxEJP9eWOaIVsdLb0uebLylVv778rPk0FQBKMuTrr1aACnV7nuDT91uNEUiLD_9K2V556HGruZJ0sCqEIH6-YRd2HFA8B6o%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 9,
            "longitude" : -0.133560001850128174,
            "price" : 1000,
            "price_currency" : "GBP",
            "price_formatted" : "1,000 GBP per week",
            "price_high" : 1000,
            "price_low" : 1000,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Newly built 3 bedroom apartment in the highly sought after embassy gardens...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/4/b/2/ad40161e9df234d3f46a46cf24a80fb64d254.1.jpg",
            "thumb_width" : 60,
            "title" : "Flat to rent, London, SW8 - En suite",
            "updated_in_days" : 2.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Rightmove",
            "guid" : "g1-TNtAzM5YzNyUDO=g",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/0/6/6/55d009586665cbc24ee6d0ae20923bb50764c.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Unfurnished, Conversion, Reception",
            "latitude" : 51.4496994018554688,
            "lister_name" : "KF&H",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=XUeYng8qp8rgrjc8z3&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmnnO6u5ws2qDemu6cetje4Le1MAjFN0MMxpoEo0SuDqCXu_ZIEd28CC1krBtbhxnBYlbaUFZ-L_2uj1ayX9zSaUA3PPm9RTFzx1PxqgQMjxnURFxT7SCTTGx45QLOrIuWu6zKhLtwCHaXnSJ3BjHaaWAreFEzfhXFT-qfRCrLDrDf6WSc-pIhgi3qlsbSL0gLeoiUJL0AptTW26OIJWtJ9LPnrfwtVQBdL-D38BHPHjErzaqIsRyKE1HAEqZL50B0-Heg89xt7XTBdjjkOAcyUA5USLLNAIjHmCNbl8ZB0GCHdCQQYWvV_o0nj7630LYCUWkeh2J8nLVYyXHwIUm4NM1PqYVcqLNX98w_kNJuZlRvsFmc7ZnEHRFxcg%3D%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.154870003461837769,
            "price" : 449,
            "price_currency" : "GBP",
            "price_formatted" : "449 GBP per week",
            "price_high" : 449,
            "price_low" : 449,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Raised ground floor garden flat to let in the Nightingale Triangle, moments...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/0/6/6/55d009586665cbc24ee6d0ae20923bb50764c.1.jpg",
            "thumb_width" : 60,
            "title" : "Ramsden Road London, SW12 - Garden",
            "updated_in_days" : 6.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 1,
            "bedroom_number" : 1,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "London2let.com",
            "guid" : "g1-TOtcDTMJjM0ITL2IQN==",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/5/9/2/f108279e534f08755f258b5475bb7ffee69a5.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Grade II, Kitchen, Georgian, Listed",
            "latitude" : 51.4735298156738281,
            "lister_name" : "Redwood",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=WbeVkd5nm5odogZ5w1&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqmnnO6u5ws2qDemu6ceNje4Le1MAfMNkMMxpoEo0SuDqCXu_ZIDMOiCCBhpABCgwbbYVHWVERwIbO22U6qD4zcZxI1J_O7Ailr1FT5s0MMpXfDJHFdsn_SHTV45hfWr56XtK7CnKd2DHGWlCF2AivUZzcsZh8rZl_ZT-7VUSqTDrCGq3mb-ZU73S75h8bSLwtRYdWLJrcCt9-N7ryweHQPvO-lt6N9Rw%3D%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 9,
            "longitude" : 0.0181000009179115295,
            "price" : 161,
            "price_currency" : "GBP",
            "price_formatted" : "161 GBP per week",
            "price_high" : 161,
            "price_low" : 161,
            "price_type" : "weekly",
            "property_type" : "house",
            "summary" : "Large bedroom available in a grade ii listed georgian house. located on the...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/5/9/2/f108279e534f08755f258b5475bb7ffee69a5.1.jpg",
            "thumb_width" : 60,
            "title" : "Bed Furnished Room London, SE3, SE3",
            "updated_in_days" : 0.5,
            "updated_in_days_formatted" : "yesterday"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Home.co.uk",
            "guid" : "g1-DOtUTM1IjN2ADMzcQN==",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/7/1/9/2e5513ce2f96650316d2ace76b39b8d606290.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Kitchen, Cottage",
            "latitude" : 51.4842796325683594,
            "lister_name" : "John Payne",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=WdeXmf7po7qfqib7y4&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmnnO6u5ws2qDemu6ceNje4Le1MAfMNkMMxpoEo0SuDqCXu_ZIDMOiCShkoQBCgwbbblbRX0RwIbO22U6qD4zcZxI1J_O7Ailr1Fr4rxhNznLRVi4MvC7CXC1g_RjOsZWUuqPKgrtwCHaTlSlwBzraaWAreFEzfhXFT-qfRCrLDrDf6X6a8J97jC2yhoOeJgkMTtWBOKZfq8nRyeeSORlI5a_25_gAVh9WOfvgglGcFjYxk_3T_gCXEVPAF6BJyFZp-Xz-p9M2vjeDKX2-bAchVgxmGLnMGonF1zhf094%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : 0.000449999992270022631,
            "price" : 415,
            "price_currency" : "GBP",
            "price_formatted" : "415 GBP per week",
            "price_high" : 415,
            "price_low" : 415,
            "price_type" : "weekly",
            "property_type" : "house",
            "summary" : "Two double bedroom period cottage is now available on the rental market...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/7/1/9/2e5513ce2f96650316d2ace76b39b8d606290.1.jpg",
            "thumb_width" : 60,
            "title" : "Hoskins Street London, SE10 - Kitchen",
            "updated_in_days" : 0.5,
            "updated_in_days_formatted" : "yesterday"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 2,
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Property Pigeon",
            "guid" : "g1-TOtUTM1AzNzETO=Y",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/0/0/c/df8a78e94b6cdc59db65c68a7a1ad47ac28dc.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Porter, Modern",
            "latitude" : 51.4618797302246094,
            "lister_name" : null,
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VUeETMoWVoXMXPIofm&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmnnO6u5ws2qDemu6ceNje4Le1MAjFN0MMxpoEo0SuDqCXu_ZIEd28CypjoBxbhxnBYlTSX15-L_2uj1ayX9zSaUA3PPm9RTFzx1f6qhhXznLRVi4MvC7CXC1g_RnOsZWSvKjDhLtwCHaUkCl1Az3aaWAreFEzfhXFT-qfRCrLDrDf6WaH8oownTblg4HWJQkQP8SLeKcb7NbQzf6ZODJCvK724_48Ul9IKODguFvWVHEvyr-Bp03JSgXNX-ERmk4%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 9,
            "longitude" : -0.223399996757507324,
            "price" : 525,
            "price_currency" : "GBP",
            "price_formatted" : "525 GBP per week",
            "price_high" : 525,
            "price_low" : 525,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Fraser and Co presents this two double bedroom apartment in the luxury...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/0/0/c/df8a78e94b6cdc59db65c68a7a1ad47ac28dc.1.jpg",
            "thumb_width" : 60,
            "title" : "London Square, Putney, SW15 - Modern",
            "updated_in_days" : 2.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : 1,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Home.co.uk",
            "guid" : "g1-DOtUTM1IjNzADNxMQM==",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/d/1/e/31957e2df5efc5a52c72f9a1513997602520a.2.jpg",
            "img_width" : 160,
            "keywords" : "",
            "latitude" : 51.4882316589355469,
            "lister_name" : "Acorn",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=VdeNcVxfexgVgYRxow&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqmnnO6u5ws2qDemu6ceNje4Le1MAfMNkMMxpoEo0SuDqCXu_ZIEd28CSxkoBhbhxnBYlrbVVV-L_2uj1ayX9zSaUA3PPm9RTFzx1P7rwQMjxnURFxT7SCTTGx45QLDqYuTtaLNhKFsDnKUkCB8BzHKZ258f099Zg2PU-qbDj_LVrDfsDid8pcwwSHz3Z3abwARY_iWM7wE7NLQ1-CYJiNC4oLh7e07ZRxXM_Dhs32KQj4xk_3T_gCXEVPAF6BJyFZp-Xz-p9M2vjeGLXm8aAchVgxmGLnMGonF1zhf094%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.0444400012493133545,
            "price" : 300,
            "price_currency" : "GBP",
            "price_formatted" : "300 GBP per week",
            "price_high" : 300,
            "price_low" : 300,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/d/1/e/31957e2df5efc5a52c72f9a1513997602520a.1.jpg",
            "thumb_width" : 60,
            "title" : "Trundleys Road London, SE8",
            "updated_in_days" : 0.5,
            "updated_in_days_formatted" : "yesterday"
         },
         {
            "auction_date" : null,
            "bathroom_number" : 1,
            "bedroom_number" : 2,
            "car_spaces" : null,
            "commission" : 0,
            "construction_year" : 0,
            "datasource_name" : "Home.co.uk",
            "guid" : "g1-DOtUTM1ITN0UzN0MgM==",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/d/0/4/ea064eb8dbc85ef79449718a076f44892c21c.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Maisonette, Refurbished, Kitchen, Reception, Modern",
            "latitude" : 51.4203681945800781,
            "lister_name" : "KF&H",
            "lister_url" : "http://rd.nestoria.co.uk/rd?itype=2&l=WdeXmf7po7qfqib7zx&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqmnnO6u5ws2qDemu6ceNje4Le1MAjFN0MMxpoEo0SuDqCXu_ZIEd28CCxipxVbhxnBYlDTVFF-L_2uj1ayX9zSaUA3PPm9RTFzx1P9qgQMjxnURFxT7SCTTGx45QLDqYuTtaLNh65sDnKUlSF1BTrPZ258f099Zg2PU-qbDj_LVrDfsDid8pcwwSHz3Z3abwARY_iWM7wE7MDDzuKPKDRU_rbM8OM-Xi9UMvrqskymVHEvyb3c8BefClSQCe1Wylxr6He379wyujKALH66ahV1AgV5SrqUB5jZ0T5MmMIR3w%3D%3D&v=2",
            "listing_type" : "let",
            "location_accuracy" : 10,
            "longitude" : -0.142389997839927673,
            "price" : 357,
            "price_currency" : "GBP",
            "price_formatted" : "357 GBP per week",
            "price_high" : 357,
            "price_low" : 357,
            "price_type" : "weekly",
            "property_type" : "flat",
            "summary" : "Newly refurbished first floor maisonette. Comprising of two bedrooms...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/d/0/4/ea064eb8dbc85ef79449718a076f44892c21c.1.jpg",
            "thumb_width" : 60,
            "title" : "Fallsbrook Road London, SW16 - Garden",
            "updated_in_days" : 0.5,
            "updated_in_days_formatted" : "yesterday"
         }
      ],
      "locations" : [
         {
            "center_lat" : 51.527243,
            "center_long" : -0.106841,
            "long_title" : "London",
            "place_name" : "london",
            "title" : "London"
         }
      ],
      "page" : "1",
      "sort" : "nestoria_rank",
      "status_code" : "200",
      "status_text" : "OK",
      "thanks" : "For using the Nestoria API.",
      "total_pages" : 2071,
      "total_results" : 41405,
      "we_are_hiring" : "http://lokku.com/#jobs"
   }
}
